# RegenStick Plugin Configuration
stick_name: "&3Healing Wand"
stick_lore:
  - "&7Aim at player and right-click to heal player for 4 &4♥&7!"
  - "&7Heals yourself instead when not aiming at a player."
  - "&7Cooldown: 5 seconds"
custom_model_data: 123
cooldown: 5
