# RegenStick Plugin Configuration
stick_name: "&3Dungeoneer's Healing Wand"
stick_lore:
  - "&7Right-click to instantly heal yourself for 25% of your &4♥&7 health!"
  - "&7Cooldown: 5 seconds"
custom_model_data: 123
cooldown: 5
