name: HealingWand
version: 1.0.1
main: com.afelia.regenstick.RegenStick
author: Elias, modded by MindFox Gaming
description: A Minecraft plugin that provides a healing wand.
api-version: '1.21' # Adjust this according to the version of Bukkit/Spigot you're using

commands:
  gethealingwand:
    description: Gives the player a healing wand.
    usage: /gethealingwand
    permission: healingwand.give

  givehealingwand:
    description: Gives a player a healing wand.
    usage: /givehealingwand <player>
    permission: healingwand.giveplayer
